routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'Auth\LoginController@showLoginForm');
Route::middleware(['auth:web', 'check-notification'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('sekolah', 'SekolahController');
    Route::resource('pangkat', 'PangkatController');
    Route::resource('pegawai', 'PegawaiController');
    Route::resource('user', 'UserController')->middleware('yayasan-middleware');

    Route::get('form-pengajuan', 'PangkatPegawaiController@form');
    Route::post('form-pengajuan', 'PangkatPegawaiController@store')->name('pengajuan.store');
    Route::get('daftar-pengajuan', 'PangkatPegawaiController@daftarPengajuan');
    Route::get('detail-pengajuan/{id}', 'PangkatPegawaiController@detailPengajuan')->name('pengajuan.detail');
    Route::put('daftar-pengajuan/{id}', 'PangkatPegawaiController@update')->name('pengajuan.update');
    Route::get('print-sk/{id}', 'PangkatPegawaiController@print')->name('pengajuan.print');

    Route::get('notifikasi', 'NotifikasiController@index');
    Route::post('update-notif', 'NotifikasiController@updateNotif');
});

app/Sekolah.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sekolah extends Model
{
    protected $table = 'sekolah';

    protected $fillable = [
        'nama_sekolah',
        'alamat',
        'no_telp',
        'nama_kepala_sekolah',
        'tahun_didirikan',
    ];

    public function pangkatPegawai()
    {
        return $this->hasMany('App\PangkatPegawai');
    }

    public function users()
    {
        return $this->belongsTo('App\User');
    }

    public static function getDefaultValues()
    {
        return [
            'nama_sekolah' => '',
            'alamat' => '',
            'no_telp' => '',
            'nama_kepala_sekolah' => '',
            'tahun_didirikan' => '',
        ];
    }

}

app/Http/Controllers/SekolahController.php
<?php

namespace App\Http\Controllers;

use App\Sekolah;
use Illuminate\Http\Request;

class SekolahController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['sekolah'] = Sekolah::orderBy('nama_sekolah', 'asc')->get();
        return view('sekolah.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['sekolah'] = (object) Sekolah::getDefaultValues();
        return view('sekolah.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_sekolah' => 'required',
            'alamat' => 'required',
            'no_telp' => 'required',
            'nama_kepala_sekolah' => 'required',
            'tahun_didirikan' => 'required',
        ]);

        Sekolah::create($request->all());
        return redirect()->route('sekolah.index')->with('success', 'Berhasil menambah data sekolah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['sekolah'] = Sekolah::find($id);
        return view('sekolah.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_sekolah' => 'required',
            'alamat' => 'required',
            'no_telp' => 'required',
            'nama_kepala_sekolah' => 'required',
            'tahun_didirikan' => 'required',
        ]);

        Sekolah::find($id)->update($request->all());
        return redirect()->route('sekolah.index')->with('success', 'Berhasil mengubah data sekolah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Sekolah::find($id)->delete();
        return redirect()->route('sekolah.index')->with('success', 'Berhasil menghapus data sekolah');
    }
}

resources/views/sekolah/form.blade.php
@extends('layouts.app')

@section('title', 'Form Sekolah')



@section('content')
<div class="row ">
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Form Sekolah</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($sekolah->id)) ? route('sekolah.store') : route('sekolah.update', $sekolah->id) }}" method="post">
                    @csrf
                    @isset($sekolah->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">
                        <label>Nama Sekolah</label>
                        <input type="text" placeholder="Nama Sekolah" class="form-control" name="nama_sekolah" value="{{ old('nama_sekolah', $sekolah->nama_sekolah) }}">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>No. Telp</label>
                                <input type="number" placeholder="No. Telp" class="form-control" name="no_telp" value="{{ old('no_telp', $sekolah->no_telp) }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tahun Didirikan</label>
                                <input type="number" placeholder="Tahun Didirikan" class="form-control" name="tahun_didirikan" value="{{ old('tahun_didirikan', $sekolah->tahun_didirikan) }}">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Alamat</label>
                        <textarea name="alamat" class="form-control" placeholder="Masukan alamat">{{ old('alamat', $sekolah->alamat) }}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Nama Kepala Sekolah</label>
                        <input type="text" placeholder="Nama Kepala Sekolah" class="form-control" name="nama_kepala_sekolah" value="{{ old('nama_kepala_sekolah', $sekolah->nama_kepala_sekolah) }}">
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/sekolah/index.blade.php
@extends('layouts.app')

@section('title', 'Sekolah')



@section('content')
<div class="row ">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Sekolah</h4>
            </div>
            <div class="card-body">
            @if(Auth::user()->level != 'tu')
            <a href="{{ route('sekolah.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Sekolah</a>
            @endif
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Sekolah</th>
                            <th>No. Telp</th>
                            <th>Alamat</th>
                            <th>Nama Kepala Sekolah</th>
                            <th>Tahun Didirikan</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($sekolah as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->nama_sekolah }}</td>
                                <td>{{ $row->no_telp }}</td>
                                <td>{{ $row->alamat }}</td>
                                <td>{{ $row->nama_kepala_sekolah }}</td>
                                <td>{{ $row->tahun_didirikan }}</td>
                                <td>
                                    @if(Auth::user()->level != 'tu')
                                    <form action="{{ route('sekolah.destroy', $row->id) }}" method="post">
                                        <ul class="d-flex action-button">
                                            <li><a href="{{ route('sekolah.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                            @csrf
                                            @method('delete')
                                            <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                        </ul>
                                    </form>
                                    @endif
                                </td>
                            </tr>

                        @empty

                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection