routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'Auth\LoginController@showLoginForm');
Route::middleware(['auth:web', 'check-notification'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('sekolah', 'SekolahController');
    Route::resource('pangkat', 'PangkatController');
    Route::resource('pegawai', 'PegawaiController');
    Route::resource('user', 'UserController')->middleware('yayasan-middleware');

    Route::get('form-pengajuan', 'PangkatPegawaiController@form');
    Route::post('form-pengajuan', 'PangkatPegawaiController@store')->name('pengajuan.store');
    Route::get('daftar-pengajuan', 'PangkatPegawaiController@daftarPengajuan');
    Route::get('detail-pengajuan/{id}', 'PangkatPegawaiController@detailPengajuan')->name('pengajuan.detail');
    Route::put('daftar-pengajuan/{id}', 'PangkatPegawaiController@update')->name('pengajuan.update');
    Route::get('print-sk/{id}', 'PangkatPegawaiController@print')->name('pengajuan.print');

    Route::get('notifikasi', 'NotifikasiController@index');
    Route::post('update-notif', 'NotifikasiController@updateNotif');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nama_lengkap', 'email', 'password', 'username', 'level', 'sekolah_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getDefaultValues()
    {
        return [
            'nama_lengkap' => '',
            'email' => '',
            'username' => '',
            'password' => '',
            'level' => '',
            'sekolah_id' => '',
        ];
    }

    public function sekolah()
    {
        return $this->belongsTo('App\Sekolah', 'sekolah_id', 'id');
    }

    public function getLevel()
    {
        if($this->level == 'tu'){
            return 'TU';
        } else {
            return 'Yayasan';
        }
    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUser;
use App\Sekolah;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $user;

    public function __construct()
    {
        $this->user = new User();
    }

    public function index()
    {
        return view ('user.index', ['users' => $this->user->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['user'] = (object) $this->user->getDefaultValues();
        $data['sekolah'] = Sekolah::orderBy('nama_sekolah', 'asc')->get();

        return view('user.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request)
    {
    	$request['password'] = bcrypt($request['password']);

        User::create($request->toArray());
        return redirect()->route('user.index')->with('success', 'Berhasil menambah data user');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['user'] = (object) $this->user->find($id);
        $data['sekolah'] = Sekolah::orderBy('nama_sekolah', 'asc')->get();
        return view('user.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUser $request, $id)
    {
        if($request['password'] == ''){
            unset($request['password']);
        } else {
            $request['password'] = bcrypt($request['password']);
        }
        $this->user->find($id)->update($request->all());
        return redirect()->route('user.index')->with('success', 'Berhasil mengubah data user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->user->find($id)->delete();
        return redirect()->route('user.index')->with('success', 'Berhasil menghapus data user');
    }
}

resources/views/user/form.blade.php
@extends('layouts.app')

@section('title', 'Form User')



@section('content')
<div class="row ">
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Form User</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($user->id)) ? route('user.store') : route('user.update', $user->id) }}" method="post">
                    @csrf
                    @isset($user->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">
                        <label>Nama Lengkap</label>
                        <input type="text" placeholder="Nama Lengkap" class="form-control" name="nama_lengkap" value="{{ old('nama_lengkap', $user->nama_lengkap) }}">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" placeholder="Username" class="form-control" name="username" value="{{ old('username', $user->username) }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" placeholder="Password" class="form-control" name="password" value="">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" placeholder="Email" class="form-control" name="email" value="{{ old('email', $user->email) }}">
                    </div>
                    <div class="form-group">
                        <label>Level</label>
                        <select name="level" id="" class="form-control">
                            <option value="">- Pilih Level -</option>
                            <option value="tu" {{ (old('level') == 'tu' || $user->level == 'tu') ? 'selected' : '' }}>TU</option>
                            <option value="yayasan" {{ (old('level') == 'yayasan' || $user->level == 'yayasan') ? 'selected' : '' }}>Yayasan</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Sekolah</label>
                        <select name="sekolah_id" id="" class="form-control">
                            <option value="">- Pilih Sekolah -</option>
                            @foreach($sekolah as $select)
                                <option value="{{ $select->id }}" {{ (old('sekolah_id') == $select->id || $user->sekolah_id == $select->id) ? 'selected' : '' }}> {{ $select->nama_sekolah }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title', 'User')



@section('content')
<div class="row ">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data User</h4>
            </div>
            <div class="card-body">
            <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah User</a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama User</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Level</th>
                            <th>Sekolah</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($users as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->nama_lengkap }}</td>
                                <td>{{ $row->username }}</td>
                                <td>{{ $row->email }}</td>
                                <td>{{ $row->getLevel() }}</td>
                                <td>{{ $row->sekolah->nama_sekolah ?? '' }}</td>
                                <td>
                                    <form action="{{ route('user.destroy', $row->id) }}" method="post">
                                        <ul class="d-flex action-button">
                                            <li><a href="{{ route('user.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                            @csrf
                                            @method('delete')
                                            <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                        </ul>
                                    </form>
                                </td>
                            </tr>
                        @empty

                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection