routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'Auth\LoginController@showLoginForm');
Route::middleware(['auth:web', 'check-notification'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('sekolah', 'SekolahController');
    Route::resource('pangkat', 'PangkatController');
    Route::resource('pegawai', 'PegawaiController');
    Route::resource('user', 'UserController')->middleware('yayasan-middleware');

    Route::get('form-pengajuan', 'PangkatPegawaiController@form');
    Route::post('form-pengajuan', 'PangkatPegawaiController@store')->name('pengajuan.store');
    Route::get('daftar-pengajuan', 'PangkatPegawaiController@daftarPengajuan');
    Route::get('detail-pengajuan/{id}', 'PangkatPegawaiController@detailPengajuan')->name('pengajuan.detail');
    Route::put('daftar-pengajuan/{id}', 'PangkatPegawaiController@update')->name('pengajuan.update');
    Route::get('print-sk/{id}', 'PangkatPegawaiController@print')->name('pengajuan.print');

    Route::get('notifikasi', 'NotifikasiController@index');
    Route::post('update-notif', 'NotifikasiController@updateNotif');
});

app/Pegawai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
    protected $table = 'pegawai';

    protected $fillable = [
        'nbm',
        'nama_lengkap',
        'tempat_lahir',
        'tgl_lahir',
        'alamat',
        'no_telp',
        'golongan',
        'jenis_pegawai', //guru, karyawan
        'j_kel',
    ];

    public function pangkatPegawai()
    {
        return $this->hasMany('App\PangkatPegawai');
    }


    public static function getDefaultValues()
    {
        return [
            'nbm' => '',
            'nama_lengkap' => '',
            'tempat_lahir' => '',
            'tgl_lahir' => '',
            'alamat' => '',
            'no_telp' => '',
            'golongan' => '',
            'jenis_pegawai' => '',
            'j_kel' => '',
        ];
    }

    public function getJKel()
    {
        if($this->j_kel == 'l'){
            return 'Laki - Laki';
        } else {
            return 'Perempuan';
        }
    }

    public function getJenisPegawai()
    {
        if($this->jenis_pegawai == 'guru'){
            return '<span class="badge badge-primary">Guru</span>';
        } else {
            return '<span class="badge badge-success">Karyawan</span>';
        }
    }
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use App\Pegawai;
use Illuminate\Http\Request;

class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['pegawai'] = Pegawai::orderBy('nama_lengkap', 'asc')->get();
        return view('pegawai.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['pegawai'] = (object) Pegawai::getDefaultValues();
        return view('pegawai.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_lengkap' => 'required',
            'tempat_lahir' => 'required',
            'tgl_lahir' => 'required',
            'alamat' => 'required',
            'no_telp' => 'required',
            'golongan' => 'required',
            'jenis_pegawai' => 'required',
            'j_kel' => 'required',
            'nbm' => 'required',
        ]);

        Pegawai::create($request->all());
        return redirect()->route('pegawai.index')->with('success', 'Berhasil menambah data pegawai');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['pegawai'] = Pegawai::find($id);
        return view('pegawai.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_lengkap' => 'required',
            'tempat_lahir' => 'required',
            'tgl_lahir' => 'required',
            'alamat' => 'required',
            'no_telp' => 'required',
            'golongan' => 'required',
            'jenis_pegawai' => 'required',
            'j_kel' => 'required',
            'nbm' => 'required',
        ]);

        Pegawai::find($id)->update($request->all());
        return redirect()->route('pegawai.index')->with('success', 'Berhasil mengubah data pegawai');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Pegawai::find($id)->delete();
        return redirect()->route('pegawai.index')->with('success', 'Berhasil menghapus data pegawai');
    }
}

resources/views/pegawai/form.blade.php
@extends('layouts.app')

@section('title', 'Form Pegawai')



@section('content')
<div class="row ">
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Form Pegawai</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($pegawai->id)) ? route('pegawai.store') : route('pegawai.update', $pegawai->id) }}" method="post">
                    @csrf
                    @isset($pegawai->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Nama Lengkap</label>
                                <input type="text" placeholder="Nama Pegawai" class="form-control" name="nama_lengkap" value="{{ old('nama_lengkap', $pegawai->nama_lengkap) }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>NBM</label>
                                <input type="text" placeholder="NBM" class="form-control" name="nbm" value="{{ old('nbm', $pegawai->nbm) }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tempat Lahir</label>
                                <input type="text" placeholder="Tempat Lahir" class="form-control" name="tempat_lahir" value="{{ old('tempat_lahir', $pegawai->tempat_lahir) }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tanggal Lahir</label>
                                <input type="text" placeholder="Tanggal Lahir" class="form-control datepicker2" name="tgl_lahir" value="{{ old('tgl_lahir', $pegawai->tgl_lahir) }}">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Jenis Kelamin</label>
                        <select name="j_kel" class="form-control mySelect">
                            <option value=""> - Pilih Jenis Kelamin - </option>
                            <option value="l" {{ (old('j_kel') == 'l' || $pegawai->j_kel == 'l') ? 'selected' : '' }}> Laki - Laki</option>
                            <option value="p" {{ (old('j_kel') == 'p' || $pegawai->j_kel == 'p') ? 'selected' : '' }}> Perempuan</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Alamat</label>
                        <textarea name="alamat" class="form-control" placeholder="Alamat">{{ old('alamat', $pegawai->alamat) }}</textarea>
                    </div>
                    <div class="form-group">
                        <label>No. Telp</label>
                        <input type="text" placeholder="No. Telp" class="form-control" name="no_telp" value="{{ old('no_telp', $pegawai->no_telp) }}">
                    </div>
                    <div class="form-group">
                        <label>Golongan</label>
                        <input type="text" placeholder="Golongan" class="form-control" name="golongan" value="{{ old('golongan', $pegawai->golongan) }}">
                    </div>
                    <div class="form-group">
                        <label>Jenis Pegawai</label>
                        <select name="jenis_pegawai" id="" class="form-control">
                            <option value="">- Pilih Jenis Pegawai -</option>
                            <option value="guru" {{ (old('jenis_pegawai') == 'guru' || $pegawai->jenis_pegawai == 'guru') ? 'selected' : '' }}>Guru</option>
                            <option value="karyawan" {{ (old('jenis_pegawai') == 'karyawan' || $pegawai->jenis_pegawai == 'karyawan') ? 'selected' : '' }}>Karyawan</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/pegawai/index.blade.php
@extends('layouts.app')

@section('title', 'Pegawai')



@section('content')
<div class="row ">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Pegawai</h4>
            </div>
            <div class="card-body">
            @if(Auth::user()->level != 'tu')
            <a href="{{ route('pegawai.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Pegawai</a>
            @endif
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Lengkap</th>
                            <th>NBM</th>
                            <th>TTL</th>
                            <th>J. Kel</th>
                            <th>Alamat</th>
                            <th>No. Telp</th>
                            <th>Golongan</th>
                            <th>Jenis Pegawai</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($pegawai as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->nama_lengkap }}</td>
                                <td>{{ $row->nbm }}</td>
                                <td>{{ $row->tempat_lahir . ', ' . $row->tgl_lahir }}</td>
                                <td>{{ $row->getJKel() }}</td>
                                <td>{{ $row->alamat }}</td>
                                <td>{{ $row->no_telp }}</td>
                                <td>{{ $row->golongan }}</td>
                                <td>{!! $row->getJenisPegawai() !!}</td>
                                <td>
                                    <form action="{{ route('pegawai.destroy', $row->id) }}" method="post">
                                        <ul class="d-flex action-button">
                                            <li><a href="{{ route('pegawai.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                            @csrf
                                            @method('delete')
                                            @if(Auth::user()->level != 'tu')
                                            <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                            @endif
                                        </ul>
                                    </form>
                                </td>
                            </tr>

                        @empty
                            <tr>
                                <td colspan="7">Belum ada data</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection