routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'Auth\LoginController@showLoginForm');
Route::middleware(['auth:web', 'check-notification'])->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('sekolah', 'SekolahController');
    Route::resource('pangkat', 'PangkatController');
    Route::resource('pegawai', 'PegawaiController');
    Route::resource('user', 'UserController')->middleware('yayasan-middleware');

    Route::get('form-pengajuan', 'PangkatPegawaiController@form');
    Route::post('form-pengajuan', 'PangkatPegawaiController@store')->name('pengajuan.store');
    Route::get('daftar-pengajuan', 'PangkatPegawaiController@daftarPengajuan');
    Route::get('detail-pengajuan/{id}', 'PangkatPegawaiController@detailPengajuan')->name('pengajuan.detail');
    Route::put('daftar-pengajuan/{id}', 'PangkatPegawaiController@update')->name('pengajuan.update');
    Route::get('print-sk/{id}', 'PangkatPegawaiController@print')->name('pengajuan.print');

    Route::get('notifikasi', 'NotifikasiController@index');
    Route::post('update-notif', 'NotifikasiController@updateNotif');
});

app/Pangkat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pangkat extends Model
{
    protected $table = 'pangkat';

    protected $fillable = [
        'nama_pangkat',
        'keterangan',
    ];

    public function pangkatPegawai()
    {
        return $this->hasMany('App\PangkatPegawai');
    }

    public static function getDefaultValues()
    {
        return [
            'nama_pangkat' => '',
            'keterangan' => '',
        ];
    }
}

app/Http/Controllers/PangkatController.php
<?php

namespace App\Http\Controllers;

use App\Pangkat;
use Illuminate\Http\Request;

class PangkatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['pangkat'] = Pangkat::orderBy('nama_pangkat', 'asc')->get();
        return view('pangkat.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['pangkat'] = (object) Pangkat::getDefaultValues();
        return view('pangkat.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_pangkat' => 'required',
        ]);

        Pangkat::create($request->all());
        return redirect()->route('pangkat.index')->with('success', 'Berhasil menambah data pangkat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['pangkat'] = Pangkat::find($id);
        return view('pangkat.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_pangkat' => 'required',
        ]);

        Pangkat::find($id)->update($request->all());
        return redirect()->route('pangkat.index')->with('success', 'Berhasil mengubah data pangkat');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Pangkat::find($id)->delete();
        return redirect()->route('pangkat.index')->with('success', 'Berhasil menghapus data pangkat');
    }
}

resources/views/pangkat/form.blade.php
@extends('layouts.app')

@section('title', 'Form Pangkat')



@section('content')
<div class="row ">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Form Pangkat</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($pangkat->id)) ? route('pangkat.store') : route('pangkat.update', $pangkat->id) }}" method="post">
                    @csrf
                    @isset($pangkat->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">
                        <label>Nama Pangkat</label>
                        <input type="text" placeholder="Nama Pangkat" class="form-control" name="nama_pangkat" value="{{ old('nama_pangkat', $pangkat->nama_pangkat) }}">
                    </div>
                    <div class="form-group">
                        <label>Keterangan</label>
                        <textarea name="keterangan" class="form-control" placeholder="Masukan keterangan">{{ old('keterangan', $pangkat->keterangan) }}</textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/pangkat/index.blade.php
@extends('layouts.app')

@section('title', 'Pangkat')



@section('content')
<div class="row ">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Pangkat</h4>
            </div>
            <div class="card-body">
            @if(Auth::user()->level != 'tu')
            <a href="{{ route('pangkat.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Pangkat</a>
            @endif
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Pangkat</th>
                            <th>Keterangan</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($pangkat as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->nama_pangkat }}</td>
                                <td>{{ $row->keterangan }}</td>
                                <td>
                                    @if(Auth::user()->level != 'tu')
                                    <form action="{{ route('pangkat.destroy', $row->id) }}" method="post">
                                        <ul class="d-flex action-button">
                                            <li><a href="{{ route('pangkat.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                            @csrf
                                            @method('delete')
                                            <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                        </ul>
                                    </form>
                                    @endif
                                </td>
                            </tr>

                        @empty

                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection